language: php

php:
  - hhvm
  - 5.6
  - 5.5
  - 5.4

matrix:
  allow_failures:
    - php: hhvm
    - php: 5.6

before_script:
  - "mkdir -p ~/.composer"
  - composer self-update
  - composer install --prefer-source --optimize-autoloader